version: '3'

services:
  kibana-elasticsearch:
    container_name: kibana-elasticsearch
    image: 'elasticsearch:6.5.4'
    restart: always
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node

  kibana-fluentd:
    container_name: kibana-fluentd
    build: ./fluentd
    volumes:
      - ./fluentd:/fluentd/etc/
    restart: always
    depends_on:
      - kibana-elasticsearch

  kibana:
    container_name: kibana
    image: kibana:6.5.4
    restart: always
    depends_on:
      - kibana-fluentd
      - kibana-elasticsearch
    environment:
      ELASTICSEARCH_URL: http://kibana-elasticsearch:9200

networks:
  default:
    external:
      name: "${DOCKER_PRIVATE_NETWORK_NAME}"